openapi: "3.0.0"
info:
  description: "The Payreq Delivery API for managing the sending of invoices\n\n
  All services communicate using JSON (JavaScript Object Notation) for transmitting data,
either as POST parameters, or within the body of the result of a GET request."
  version: "v2"
  title: "Payreq API"
servers:
  - url: "https://test.payreq.com/api/v2"
  - url: "http://go.payreq.localhost/api/v2"
paths:
  /token:
    post:
      tags:
      - "Authentication"
      summary: "Get an api authenication token"
      description: "In order to access a Payreq web service, you must first be authenticated within the
Payreq system. This process involves submitting your credentials to a known endpoint to
retrieve a token, which will be used for authentication for subsequent web service calls.\n\n
The token must be submitted within the Authorisation http header for each subsequent
request to a Payreq web service as Token <token returned by call>.\n\n
If using Swagger add authorise add Token aaabbbcccdddeeefffggg. Assuming aaabbbcccdddeeefffggg was returned your call to this API. \n\n
Note: authentication tokens are valid for a maximum of 15 minutes."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Auth"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseToken"
        "400":
          description: "error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"

  /accounts/{type}:
    get:
      tags:
        - "Accounts"
      summary: "Accounts Visible to API User"
      description: "Get details of the accounts the API user has access  to by  type delivery, inbox or mypay."
      parameters:
        - in: "path"
          name: "type"
          description: "Account Type"
          required: true
          schema:
            type: "string"
        - in: "query"
          name: "page-number"
          description: "Page number defaults to 1 if not provided"
          schema:
            type: integer
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                    $ref: "#/components/schemas/ResponseAccounts"
        "400":
          description: "Invalid parameter"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseErrorV3"
        "401":
          description: "Permission denied"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: [ ]

  /biller/{biller-code}/registrations/current:
    get:
      tags:
      - "Registrations"
      summary: "Get all active registrations"
      description: "Return all current registered payers for a sender, along with the total count"
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseRegistrations"
        "400":
          description: "Payreq unable to return registrations at this time as Agent registrations still processing."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationError"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/registrations/{account-number}/check:
    get:
      tags:
        - "Registrations"
      summary: "Check if account number has an active registration"
      description: "Returns active equals true if there is an active registration for the account number"
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "string"
        - in: "path"
          name: "account-number"
          description: "Account Number"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseCheckRegistration"
        "400":
          description: "Payreq unable to return registrations at this time as Agent registrations still processing."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationError"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/contacts/add:
    post:
      tags:
      - "Contacts"
      summary: "Add contacts"
      description: "Add (and update) contacts for the sender \n\n
      If a contact already exists with the given biller-account-number for the biller, then the
details of that contact will be replaced. Otherwise, the contact will be added."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "integer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contacts"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseImported"
        "400":
          description: "error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseErrorContactsAdd"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/contacts/replace:
    post:
      tags:
      - "Contacts"
      summary: "Replace contacts"
      description: "Replaces the contacts for the sender with the new contacts."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "integer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contacts"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseImported"
        "400":
          description: "error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseErrorContactsReplace"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/contacts/job/add:
    post:
      tags:
      - "Contacts"
      summary: "Add contacts as a job"
      description: "Add (and update) contacts for the sender \n\n
      If a contact already exists with the given biller-account-number for the biller, then the
details of that contact will be replaced. Otherwise, the contact will be added. \n\n
      To avoid timeout issues for a sender with a large number of contacts this API is
recommended. Once you submit the contact job poll its completion using the job
status update API."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "integer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contacts"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseImportedJob"
        "400":
          description: "error"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ResponseErrorV2"
                  - $ref: "#/components/schemas/ResponseErrorV3"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/contacts/job/replace:
    post:
      tags:
      - "Contacts"
      summary: "Replace contacts as a job"
      description: "Replaces the contacts for the sender with the new contacts.\n\n
      To avoid timeout issues for a sender with a large number of contacts this API is
recommended. Once you submit the contact job poll its completion using the job
status update API.\n\n
      To avoid timeout issues for a sender with a large number of contacts this API is
recommended. Once you submit the contact job poll its completion using the job
status update API."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "integer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contacts"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseImportedJob"
        "400":
          description: "error"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ResponseErrorV2"
                  - $ref: "#/components/schemas/ResponseErrorV3"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/jobs/{job-id}:
    get:
      tags:
      - "Jobs"
      summary: "Get job details"
      description: "Get the details and current status of the specified job."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "string"
        - in: "path"
          name: "job-id"
          description: "Job ID"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseJob"
        "404":
          description: "No job found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/jobs/{job-id}/delivery-summary:
    get:
      tags:
        - "Jobs"
      summary: "Get document delivery information for job"
      description: "Get information about where documents for the job were delivered."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "string"
        - in: "path"
          name: "job-id"
          description: "Job ID"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseJobDeliverySummary"
        "404":
          description: "No job found or all documents not dispatched"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/jobs:
    post:
      tags:
      - "Jobs"
      summary: "Submit bill job"
      description: "Notify Payreq that a file is ready to be picked up from the sender/mailhouse SFTP server,
or that a file has been recently copied to the working directory on the Payreq SFTP
server. This will create a Job in the Payreq system for tracking the progress of the
processing of the file.\n\n
A few things to note:\n\n
• If the file could not be found on the remote SFTP server or the working directory of
the Payreq SFTP server, there is no mechanism to flag this within the Job that is
created by this service, and the job will persist in status “pending-file”. However, if
the file transfer fails during this process, an alert will be sent to the Payreq ops
team, so appropriate action will be taken if required.\n\n
• The Job created by this service can be viewed and progress tracked in the Payreq
Admin console.\n\n
• The transfer of the file does not occur immediately after this service is executed –
the task to pickup the file is queued by the system to be performed in the future.
The delay is generally only a few minutes at the most.\n\n
• The only file supported for this service at the moment is the BILL_LOAD and
PAYROLL_LOAD tar file."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmitJob"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseImportedJob"
        "400":
          description: "error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseErrorV3"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/bills/nondelivered/submitted:
    get:
      tags:
      - "Documents"
      summary: "Non-delivered Documents - search by Date Submitted"
      description: "Search for document for a sender that were unable to be delivered to a recipient, where
the document was received by Payreq (submitted to Payreq) during the given interval."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "string"
        - in: "query"
          name: "from"
          description: "Bills send from date/timestamp as UTC"
          schema:
            type: string
            format: "yyyyMMddHHmm"
        - in: "query"
          name: "to"
          description: "Bills send from date/timestamp as UTC"
          schema:
            type: string
            format: "yyyyMMddHHmm"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseDocumentNondelivered"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/bills/nondelivered/returned:
    get:
      tags:
        - "Documents"
      summary: "Non-delivered Documents - search by Date Non-Delivery was Received"
      description: "Search for document for a sender that were unable to be delivered to a recipient, where
the document was marked as undeliverable by Payreq during the given interval."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "string"
        - in: "query"
          name: "from"
          description: "Bills returned from date/timestamp as UTC"
          schema:
            type: string
            format: "yyyyMMddHHmm"
        - in: "query"
          name: "to"
          description: "Bills returned to date/timestamp as UTC"
          schema:
            type: string
            format: "yyyyMMddHHmm"
        - in: "query"
          name: "all-nondelivered-emails"
          description: "Return all bounced email deliveries in the specified to/from time period"
          schema:
            type: boolean
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseDocumentNondelivered"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /biller/{biller-code}/bills/{bill-id}/action:
    post:
      tags:
      - "Documents"
      summary: "Action Documents – add external actions"
      description: "For the non-delivered documents, can add an external action."
      parameters:
        - in: "path"
          name: "biller-code"
          description: "Biller Code"
          required: true
          schema:
            type: "string"
        - in: "path"
          name: "bill-id"
          description: "ID of bill to upate"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResponseActionNondeliverableDocument"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseNondeliverableUpdate"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

  /mybills/{account-id}/bills:
    get:
      tags:
        - "Payreq Inbox"
      summary: "Bills - search by Received Date"
      description: "Search for invoices by received date."
      parameters:
        - in: "path"
          name: "account-id"
          description: "MyBills Account Id"
          required: true
          schema:
            type: "string"
        - in: "query"
          name: "from-date"
          description: "Bills received from date"
          schema:
            type: string
            format: "yyyyMMddHHmm"
        - in: "query"
          name: "to-date"
          description: "Bills received to date"
          schema:
            type: string
            format: "yyyyMMddHHmm"
        - in: "query"
          name: "page-number"
          description: "Page number defaults to 1 if not provided"
          schema:
            type: integer
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseBills"
        "400":
          description: "Invalid parameter"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseErrorV3"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []
  /mybills/{account-id}/bills/{id}:
    get:
      tags:
        - "Payreq Inbox"
      summary: "Bill detail by id"
      description: "Get bill detail for an invoice by id."
      parameters:
        - in: "path"
          name: "account-id"
          description: "MyBills Account Id"
          required: true
          schema:
            type: "string"
        - in: "path"
          name: "id"
          description: "Bill id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseBillDetail"
        "404":
          description: "Bill ID not found in biller"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "500":
          description: "system error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemError"
      security:
        - payreq_auth: []

components:
  securitySchemes:
    payreq_auth:
      type: "apiKey"

      in: "header"
      name: "Authorization"
  schemas:
    Auth:
      type: "object"
      required:
        - "user"
        - "password"
      properties:
        user:
          type: "string"
        password:
          type: "string"
      example:
        user: "person1@company.com"
        password: "password"
    ResponseToken:
      type: "object"
      properties:
        token:
          type: "string"
      example:
        token: "eyJhb...snip"
    ResponseCheckRegistration:
      type: "object"
      properties:
        active:
          type: "boolean"
        agent-active:
          type: "boolean"
        owner-active:
          type: "boolean"
        meta:
          type: "object"
          properties:
            params:
              type: "object"
              properties:
                account-number:
                  type: "string"
      example:
        active: true
        meta:
          params:
              account-number: "12348"

    ResponseRegistrations:
      type: "object"
      properties:
        count:
          type: "integer"
          format: "int32"
        biller-code:
          type: "string"
        payers:
          type: "array"
          items:
            $ref: '#/components/schemas/Payer'
      example:
        count: 2
        biller-code: "9999"
        payers:
          - biller-account-number: "999888777"
            customer-full-name: "Steve Smith"
            auth-item-1: "Mr S Smith"
            agent-active: true
            owner-active: true
          - biller-account-number: "999889874"
            customer-full-name: "Bob Jones"
            auth-item-1: "Mr B Jones"
            agent-ative: false
            owner-active: true
    Payer:
      type: "object"
      properties:
        biller-account-number:
          type: "string"
        customer-full-name:
          type: "string"
        auth-item-1:
          type: "string"
        auth-item-2:
          type: "string"
        auth-item-3:
          type: "string"
        auth-item-4:
          type: "string"
        agent-active:
          type: "boolean"
        owner-active:
          type: "boolean"

    ResponseImported:
      type: "object"
      properties:
        count:
          type: "integer"
        biller-code:
          type: "string"
      example:
        count: 3
        biller-code: "9999"
    ResponseImportedJob:
      type: "object"
      properties:
        job:
          type: "object"
          properties:
            id:
              type: "integer"
      example:
        job:
          id: 9281
    Contacts:
      type: "array"
      items:
        $ref: '#/components/schemas/Contact'
      example:
        - biller-account-number: "999888777"
          name: "Steve Smith"
          contact-id-1: "999888777"
          contact-id-2: "Mr S Smith"
        - biller-account-number: "999889874"
          name: "Bob Jones"
          contact-id-1: "999889874"
          contact-id-2: "Mr B Jones"
    Contact:
      type: "object"
      required:
        - biller-account-number
        - name
      properties:
        biller-account-number:
          type: "string"
        name:
          type: "string"
        contact-id-1:
          type: "string"
        contact-id-2:
          type: "string"
        contact-id-3:
          type: "string"
        contact-id-4:
          type: "string"
        contact-id-5:
          type: "string"
        contact-id-6:
          type: "string"
        address-1:
          type: "string"
        address-2:
          type: "string"
        municipality:
          type: "string"
        province:
          type: "string"
        country:
          type: "string"
        postal-code:
          type: "string"
        business-identifier:
          type: "string"
    ResponseJob:
      type: "object"
      properties:
        job:
          type: "object"
          properties:
            status:
              type: "string"
              enum: [done, error, in-progress]
            start-date:
              type: "string"
              format: "date-time"
            end-date:
              type: "string"
              format: "date-time"
            description:
              type: "string"
            file-hash:
              type: "string"
      example:
        status: "done"
        start-date: "2020-07-15T04:50:40Z"
        end-date: "2020-07-15T04:59:40Z"
        description: "Completed: add_20160623065438.csv"
        file-hash: "aabbvv...snip"
    ResponseJobDeliverySummary:
      type: "object"
      properties:
        biller:
          type: "object"
          properties:
            name:
              type: "string"
            biller-code:
              type: "string"
        delivery-summary:
          type: "object"
          properties:
            dispatch-type:
              type: "array"
              items:
                type: "string"
            documents-sent:
              type: "integer"
            bpv-qty-raw:
              type: "integer"
            email-qty-raw:
              type: "integer"
            myob-qty-raw:
              type: "integer"
            xero-qty-raw:
              type: "integer"
            reckon-qty-raw:
              type: "integer"
            mybills-qty-raw:
              type: "integer"
            mybillsagent-qty-raw:
              type: "integer"
        meta:
          type: "object"
          properties:
            job-id:
              type: "integer"
      example:
        biller:
          - name: "Demo Council"
            biller-code: "12872"
        delivery-summary:
          - dispatch-type: ["bpv", "email"]
            documents-sent: 1
            bpv-qty-raw: 1
            email-qty-raw: 2
            myob-qty-raw: 0
            xero-qty-raw: 0
            reckon-qty-raw: 0
            mybills-qty-raw: 0
            mybillsagent-qty-raw: 0
          - dispatch-type: ["bpv"]
            documents-sent: 10
            bpv-qty-raw: 10
            email-qty-raw: 0
            myob-qty-raw: 0
            xero-qty-raw: 0
            reckon-qty-raw: 0
            mybills-qty-raw: 0
            mybillsagent-qty-raw: 0
        meta:
          - job-id: 10
    SubmitJob:
      type: "object"
      properties:
        file-name:
          type: "string"
          description: "The package filename to be picked up from the SFTP working directory. EG. bill_load_20201216.tar"
        file-hash:
          type: "string"
          description: "openssl sha1 bill_index.csv | sed -E 's/.+=(.+)/\\1/'"
      example:
        file-name: "bills_dec_2016.tar"
        file-hash: "fdkfldjs...hshk"
    ResponseDocumentNondelivered:
      type: "object"
      properties:
        biller:
          type: "object"
          properties:
              name:
                type: "string"
              biller-code:
                type: "string"
        count:
          type: "string"
        non-delivered-documents:
          type: "array"
          items:
            $ref: '#/components/schemas/NondeliveredDocument'
        meta:
          type: "object"
          properties:
            total-non-delivered:
              type: "integer"
            params:
              type: "object"
              properties:
                from:
                  type: "string"
                  format: "datetime"
                to:
                  type: "string"
                  format: "datetime"
                all-nondelivered-emails:
                  type: "boolean"
      example:
        biller:
          name: "Energy Australia"
          biller-code: "92822"
        non-delivered-documents:
          - bill-id: 129
            biller-invoice-number: "INV19280"
            mailhouse-document-id: "29239093"
            due-date: "2021-05-28"
            due-date-total: "2022-02-15"
            non-delivered:
              - dispatch-type: "email"
                non-delivered-time: "2021-04-14T04:59:39Z"
                non-delivered-reason-code: "email/undeliverable"
                actioned-time: "2021-04-12T02:59:39Z"
                emails-sent: 2
                emails-bounced: 1
                emails-bounced-details:
                  - email: "bademail@bad.com"
                    email-non-delivered-time: "2021-04-14T04:59:39Z"
            delivered:
              -
            total-non-delivered: 1
            total-delivered: 0
          - bill-id: 389
            biller-invoice-number: "INV19992"
            mailhouse-document-id: "49239003"
            due-date: "2021-05-28"
            due-date-total: "2022-02-15"
            non-delivered:
              - dispatch-type: "myob"
                non-delivered-time: "2021-04-14T04:31:39Z"
                non-delivered-reason-code: "myob/undeliverable"
                actioned-time: "2021-04-14T02:59:39Z"
            delivered:
              - dispatch-type: "bpv"
                actioned-time: "2021-04-14T01:59:39Z"
            total-non-delivered: 1
            total-delivered: 1
        meta:
          total-non-delivered: 2
          params:
            from: "2021-04-14T00:00:00Z"
            to: "2021-04-14T14:00:00Z"
            all-nondelivered-emails: false
    NondeliveredDocument:
      type: "object"
      properties:
        bill-id:
          type: "integer"
        biller-invoice-number:
          type: "string"
        mailhouse-document-id:
          type: "string"
        due-date:
          type: "string"
          format: "date"
        due-date-total:
          type: "string"
          format: "date"
        job-id:
          type: "integer"
        non-delivered:
          type: "array"
          items:
            $ref: '#/components/schemas/Nondelivered'
        delivered:
          type: "array"
          items:
            $ref: '#/components/schemas/Delivered'
        total-non-delivered:
          type: "integer"
        total-delivered:
          type: "integer"
    Nondelivered:
      type: "object"
      properties:
        dispatch-type:
          type: "string"
        non-delivered-reason-code:
          description: |
            Code       | Applies to Channel | Description
            ------------ | ------------- | -------------
            invalid-expiry-date | bpv | Expiry date for bill is invalid
            invalid-creation-date | bpv | Creation date for bill is invalid
            invalid-payer-account | bpv | Payer account is invalid
            olb-failed-to-email-payer | bpv | The payer’s online bank could not send an email notification to the payer.
            olb-failed-to-deliver-billsummary | bpv | The online bank could not present the bill to the payer
            bpv-failed-to-deliver-billsummary-to-olb | bpv | Bpay View could not forward the bill to the payer’s online bank
            not-owner-manager | all except bpv, epost and einvoicing | No longer own or manage the property.
            epost/unidentified | epost | An unknown error occurred
            epost/invalid-accntno | epost | The account number for the payer was invalid
            epost/closed-ebox | epost | The ebox for the account has been closed
            epost/invalid-ebox | epost | The ebox for the account is invalid
            epost/wrong-ebox | epost | The recipient has bounced back the document – wrong recipient
            epost/closed-subscription | epost | The payer’s subscription to the document has been closed
            xeroconnect/undeliverable | xero | The document could not be delivered to the Payers Xero account
            xeroconnect/no-active-registration | xero | The document could not be delivered as there is no longer and active registration
            myob/undeliverable | myob | The document could not be delivered to the Payers MYOB account
            myob/no-active-registration | myob | The document could not be delivered as there is no longer and active registration
            reckon/undeliverable | reckon | The document could not be delivered to the Payers Reckon account
            reckon/no-active-registration | reckon | The document could not be delivered as there is no longer and active registration
            einvoicing/undeliverable | einvoicing | The document could not be delivered to the Payers E-Invoicing account
            einvoicing/duplicate-invoice-number | einvoicing | The document could not be delivered as the invoice number is the same as one previously sent
            email/undeliverable | email | The document could not be delivered to the registered email
            email/no-active-email-addresses | email | The document could not be delivered as there is no lonnger an active registration
            mybillsagent/undeliverable | mybillsagent | The document could not be delivered to the registered Payreq Inbox
            mybillsagent/no-active-registration | mybillsagent | The document could not be delivered as there is no longer and active registration
            mybills/undeliverable | mybills | The document could not be delivered to the registered Payreq Inbox
            mybills/no-active-registration | mybills | The document could not be delivered as there is no longer and active registration
            archive/undeliverable | archive | The archived document could not be delivered to the registered Payreq Inbox
            archive/no-active-registration | archive | The document could not be delivered as there is no longer and active registration

          type: "string"
        actioned-time:
          type: "string"
          format: "date-time"
        non-delivered-time:
          type: "string"
          format: "date-time"
        emails-bounced-details:
          type: "array"
          items:
            $ref: '#/components/schemas/NondeliverdEmail'
        emails-sent:
          type: "integer"
        emails-bounced:
          type: "integer"
    Delivered:
      type: "object"
      properties:
        dispatch-type:
          type: "string"
        actioned-time:
          type: "string"
          format: "date-time"
    NondeliverdEmail:
      type: "object"
      properties:
        email:
          type: "string"
        email-non-delivered-time:
          type: "string"
          format: "date-time"
    ResponseActionNondeliverableDocument:
      type: "object"
      properties:
        bill-id:
          type: "integer"
        action-description:
          type: "string"
      example:
        bill-id: 2827
        action-description: "Printed and posted"
    ResponseNondeliverableUpdate:
      type: "object"
      properties:
        actioned-on:
          type: "string"
          format: "datetime"
        action-description:
          type: "string"
      example:
        actioned-on: "2020-05-01T00:19:04Z"
        action-description: "Printed and posted"
    SystemError:
      type: "object"
      properties:
        success:
          type: "boolean"
        error:
          type: "object"
          properties:
            id:
              type: "string"
      example:
        success: false
        error:
          id: "011b96fc-fbaa-486b-946e-128c516cbe9b"
    RegistrationError:
      type: "object"
      properties:
        error:
          type: "string"
      example:
        error: "Agent registrations pending processing"
    ResponseError:
      type: "object"
      properties:
        message:
          type: "string"
      example:
        message: "The error message."
    ResponseErrorV2:
      type: "object"
      properties:
        errors:
          type: "string"
      example:
        errors: [":invalid-data-format"]
    ResponseErrorV3:
      type: "object"
      properties:
        error:
          type: "string"
      example:
        error: "An error message"
    ResponseErrorContactsReplace:
      type: "object"
      properties:
        errors:
          type: "string"
          description: |
            Result       | Description
            ------------ | -------------
            {"errors":["insufficient-commoncontacts"]} | Validation check to ensure there is only a 20% difference between the contacts that exist and the new contacts in the json being uploaded has failed, resulting in a validation error.
            {"errors":["invalid-data-format"]} | Json body contains incorrectly formatted data.
            {"errors":["invalid-biller-accountnumber-length"]} | The biller-account-number field contains data that isn’t the correct length specified by the biller on setup, resulting in a validation error.
            {"errors":["duplicate-biller-accountnumber"]} | There is a duplicate value for biller-account-number causing a validation error.
    ResponseErrorContactsAdd:
      type: "object"
      properties:
        errors:
          type: "string"
          description: |
            Result       | Description
            ------------ | -------------
            {"errors":["invalid-data-format"]} | Json body contains incorrectly formatted data.
            {"errors":["invalid-biller-accountnumber-length"]} | The biller-account-number field contains data that isn’t the correct length specified by the biller on setup, resulting in a validation error.
            {"errors":["duplicate-biller-accountnumber"]} | There is a duplicate value for biller-account-number causing a validation error.

    ResponseBills:
      type: "object"
      properties:
        bills:
          type: "array"
          items:
            $ref: '#/components/schemas/ResponseBillSummary'
        meta:
          type: "object"
          properties:
            total:
              type: "integer"
            total-pages:
              type: "integer"
            params:
              type: "object"
              properties:
                from-date:
                  type: "string"
                  format: "date-time"
                to-date:
                  type: "string"
                  format: "date-time"
                page-number:
                  type: "integer"
                num-records:
                  type: "integer"
      example:
        bills:
          - id: 2
            description: "Invoice from Demo Company for work"
            min-amount-due: null
            currency-code: "AUD"
            status: "payment-due"
            received-by: "payreq"
            due-date: "2021-02-20"
            invoice-number: "INV-092"
            received-time: "2021-01-20 13:28:01"
            amount-due: 102.98
        meta:
          total: 1
          total-pages: 1
          params:
            from-date: null
            to-date: "2021-01-25 02:30:54"
            page-number: 1
            num-records: 100

    ResponseBillSummary:
      type: "object"
      properties:
        id:
          type: "integer"
        description:
          type: "string"
        min-amount-due:
          type: "number"
        currency-code:
          type: "string"
        status:
          type: "string"
          enum: ["payment-due", "paid", "no-payment-due", "payment-network-error"]
        received-by:
          type: "string"
        due-date:
          type: "string"
          format: "date"
        invoice-no:
          type: "string"
        received-time:
          type: "string"
          format: "date-time"
        amount-due:
          type: "number"

    ResponseBillDetail:
      type: "object"
      properties:
        id:
          type: "integer"
        description:
          type: "string"
        min-amount-due:
          type: "number"
        currency-code:
          type: "string"
        status:
          type: "string"
          enum: [ "payment-due", "paid", "no-payment-due", "payment-network-error" ]
        received-by:
          type: "string"
        due-date:
          type: "string"
          format: "date"
        invoice-no:
          type: "string"
        received-time:
          type: "string"
          format: "date-time"
        amount-due:
          type: "number"
        pdf-base-64:
          type: "string"
        bill-detail:
          type: "object"
          description: "See invoicing spec for details"
      example:
        id: 2
        description: "Invoice from Demo Company for work"
        min-amount-due: null
        currency-code: "AUD"
        status: "payment-due"
        received-by: "payreq"
        due-date: "2021-02-20"
        invoice-number: "INV-092"
        received-time: "2021-01-20 13:28:01"
        amount-due: 102.98
        pdf-base-64: "binary file as base 64"
        bill-detail: "See invoicing spec for details"
    ResponseAccounts:
      type: "object"
      properties:
        accounts:
          type: "array"
          items:
            $ref: '#/components/schemas/ResponseAccountDetails'
        meta:
          type: "object"
          properties:
            total:
              type: "integer"
            total-pages:
              type: "integer"
            params:
              type: "object"
              properties:
                type:
                  type: "string"
                page-number:
                  type: "integer"
                num-records:
                  type: "integer"
      example:
        accounts:
          - id: 2
            name: "My Payreq MyBills Account"
            tax-id: "12345678912"
            ext-biller-id: null
            document-location-id: 1
            country-id: "au"
            state-id: null
        meta:
          total: 1
          total-pages: 1
          params:
            type: "inbox"
            page-number: 1
            num-records: 100
    ResponseAccountDetails:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        tax-id:
          type: "string"
        ext-biller-id:
          type: "string"
        document-location-id:
          type: "integer"
          description: "1 = Australia, 2 = Canada, 3 = UK"
        country-id:
          type: "string"
        state-id:
          type: "string"


externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
